import {
  API_URL,
  ENVIRONMENT,
  USE_MOCK_DATA,
  LOG_NETWORK_REQUEST,
  LOG_REDUX_ACTIONS,
  NETWORK_REQUEST_TIMEOUT_IN_SEC,
} from "@app/_env.json";

export default {
  IS_DEBUG: __DEV__,
  ENVIRONMENT,
  API_URL,
  USE_MOCK_DATA,
  LOG_REDUX_ACTIONS,
  LOG_NETWORK_REQUEST,
  NETWORK_REQUEST_TIMEOUT_IN_SEC,
};
