export default {
  MAX_WIDTH: 1024,
  DEFAULT_TOTAL_ITEM: 1000,
  DEFAULT_PAGE_SIZE: 20,
  FIRST_PAGE_NUMBER: 0,
  DATE_FORMAT_RFC_1123: "EEE, DD MMM YYYY HH:mm:ss z",
  DATE_FORMAT_ISO_8601_DATE: "YYYY-MM-DD",
  DATE_FORMAT_ISO_8601_DATE_TIME: "YYYY-MM-DD'T'HH:mm:ssZ",
  DATE_FORMAT_ISO_8601_DATE_TIME_NO_TIMEZONE: "YYYY-MM-DD'T'HH:mm:ss",
  DATE_FORMAT_ISO_8601_DATE_TIME_MILLIS: "YYYY-MM-DD'T'HH:mm:ss.SSSZ",
  DATE_FORMAT_ISO_8601_DATE_TIME_MILLIS_NO_TIMEZONE:
    "YYYY-MM-DD'T'HH:mm:ss.SSS",
  OTP_NUMBER_COUNT: 5,
  RESEND_OTP_TIMER_IN_SEC: 60,
  HEADER_LIST_GRID_OPTION_KEY: "X-GridOption",
  HEADER_LANG_KEY: "Accept-Language",
  HEADER_AUTH_TOKEN_KEY: "X-AuthToken",
  HEADER_USER_AGENT_KEY: "User-Agent",
  HEADER_BODY_KEY: "X-Body"
};

